name: Continuous Deployment
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
          
            - name: Setup NodeJs
              uses: actions/setup-node@v2-beta
              with:
               node-version: 12.1
            - name: github action for yarn
              uses: Borales/actions-yarn@v2.1.0
              with:
                cmd: install 
             
          
            - name :   nowyarn build
              run   :  yarn build
          
            - name: install surge
              run: npm install -g surge
            - name : deploy on surge
              run : surge ./build comfortable-smoke.surge.sh --token 3c57bc299bb41259e51f9bf6e8652b20

